/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package s1_java_efm;

import java.awt.BorderLayout;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author yalam
 */
public class Dashboard extends javax.swing.JFrame {

    private static Dashboard instance;
    private Connection con;
    private PreparedStatement pst;
    private ResultSet rs;
    private String name;
    private String role;
    private int id;
    int clubId = 0;
    ArrayList<Integer> ids;

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        if (instance == null) {
            instance = this;
        }
    }

    public Dashboard(int id, String name, String role) {
        initComponents();
        if (instance == null) {
            instance = this;
        }
        this.name = name;
        this.role = role;
        this.id = id;
    }

    public static Dashboard getInstance() {
        if (instance == null) {
            instance = new Dashboard();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUserName = new javax.swing.JLabel();
        btnClubs = new javax.swing.JButton();
        btnEvents = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnMyClub = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblClubName1 = new javax.swing.JLabel();
        lblClubName5 = new javax.swing.JLabel();
        txtGerant1 = new javax.swing.JTextField();
        lblMembreCount1 = new javax.swing.JLabel();
        btnClub1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblClubName2 = new javax.swing.JLabel();
        lblClubName6 = new javax.swing.JLabel();
        txtGerant2 = new javax.swing.JTextField();
        lblMembreCount2 = new javax.swing.JLabel();
        btnClub2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblClubName3 = new javax.swing.JLabel();
        lblClubName7 = new javax.swing.JLabel();
        txtGerant3 = new javax.swing.JTextField();
        lblMembreCount3 = new javax.swing.JLabel();
        btnClub3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lblClubName4 = new javax.swing.JLabel();
        lblClubName8 = new javax.swing.JLabel();
        txtGerant4 = new javax.swing.JTextField();
        lblMembreCount4 = new javax.swing.JLabel();
        btnClub4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblEventTitle1 = new javax.swing.JLabel();
        lblParticipants1 = new javax.swing.JLabel();
        btnEvent1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        lblEventTitle2 = new javax.swing.JLabel();
        lblParticipants2 = new javax.swing.JLabel();
        btnEvent2 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        lblEventTitle3 = new javax.swing.JLabel();
        lblParticipants3 = new javax.swing.JLabel();
        btnEvent3 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        lblEventTitle4 = new javax.swing.JLabel();
        lblParticipants4 = new javax.swing.JLabel();
        btnEvent4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion des clubs");
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(52, 73, 94));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lblUserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserName.setText("Youssef El hardouzi");

        btnClubs.setBackground(new java.awt.Color(41, 128, 185));
        btnClubs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClubs.setText("Clubs");
        btnClubs.setFocusPainted(false);
        btnClubs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClubsActionPerformed(evt);
            }
        });

        btnEvents.setBackground(new java.awt.Color(41, 128, 185));
        btnEvents.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEvents.setText("Evenements");
        btnEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventsActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(41, 128, 185));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Se deconnecter");

        btnMyClub.setBackground(new java.awt.Color(41, 128, 185));
        btnMyClub.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMyClub.setText("Mon club");
        btnMyClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyClubActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClubs, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMyClub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEvents, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClubs, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMyClub, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEvents, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 240));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(236, 240, 241));
        jPanel3.setPreferredSize(new java.awt.Dimension(120, 120));

        lblClubName1.setBackground(new java.awt.Color(52, 152, 219));
        lblClubName1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblClubName1.setForeground(new java.awt.Color(44, 62, 80));
        lblClubName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClubName1.setText("jLabel2");

        lblClubName5.setBackground(new java.awt.Color(52, 99, 196));
        lblClubName5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblClubName5.setForeground(new java.awt.Color(44, 62, 80));
        lblClubName5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClubName5.setText("Gerant:");

        txtGerant1.setEditable(false);
        txtGerant1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGerant1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtGerant1.setEnabled(false);

        lblMembreCount1.setBackground(new java.awt.Color(52, 152, 219));
        lblMembreCount1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMembreCount1.setForeground(new java.awt.Color(44, 62, 80));
        lblMembreCount1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMembreCount1.setText("Membres : ");

        btnClub1.setBackground(new java.awt.Color(52, 152, 219));
        btnClub1.setForeground(new java.awt.Color(44, 62, 80));
        btnClub1.setText("Detail");
        btnClub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClub1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMembreCount1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGerant1)
                    .addComponent(lblClubName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblClubName5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnClub1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClubName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClubName5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGerant1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMembreCount1)
                .addGap(18, 18, 18)
                .addComponent(btnClub1)
                .addGap(122, 122, 122))
        );

        jPanel4.setBackground(new java.awt.Color(236, 240, 241));
        jPanel4.setForeground(new java.awt.Color(44, 62, 80));
        jPanel4.setPreferredSize(new java.awt.Dimension(120, 120));

        lblClubName2.setBackground(new java.awt.Color(52, 152, 219));
        lblClubName2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblClubName2.setForeground(new java.awt.Color(44, 62, 80));
        lblClubName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClubName2.setText("jLabel3");

        lblClubName6.setBackground(new java.awt.Color(52, 99, 196));
        lblClubName6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblClubName6.setForeground(new java.awt.Color(44, 62, 80));
        lblClubName6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClubName6.setText("Gerant:");

        txtGerant2.setEditable(false);
        txtGerant2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGerant2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtGerant2.setEnabled(false);

        lblMembreCount2.setBackground(new java.awt.Color(52, 152, 219));
        lblMembreCount2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMembreCount2.setForeground(new java.awt.Color(44, 62, 80));
        lblMembreCount2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMembreCount2.setText("Membres : ");

        btnClub2.setBackground(new java.awt.Color(52, 152, 219));
        btnClub2.setForeground(new java.awt.Color(44, 62, 80));
        btnClub2.setText("Detail");
        btnClub2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClub2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtGerant2)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClubName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblClubName6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblMembreCount2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnClub2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClubName2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClubName6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGerant2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMembreCount2)
                .addGap(18, 18, 18)
                .addComponent(btnClub2)
                .addGap(90, 90, 90))
        );

        jPanel5.setBackground(new java.awt.Color(236, 240, 241));
        jPanel5.setPreferredSize(new java.awt.Dimension(120, 120));

        lblClubName3.setBackground(new java.awt.Color(52, 152, 219));
        lblClubName3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblClubName3.setForeground(new java.awt.Color(44, 62, 80));
        lblClubName3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClubName3.setText("jLabel4");

        lblClubName7.setBackground(new java.awt.Color(52, 99, 196));
        lblClubName7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblClubName7.setForeground(new java.awt.Color(44, 62, 80));
        lblClubName7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClubName7.setText("Gerant:");

        txtGerant3.setEditable(false);
        txtGerant3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGerant3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtGerant3.setEnabled(false);

        lblMembreCount3.setBackground(new java.awt.Color(52, 152, 219));
        lblMembreCount3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMembreCount3.setForeground(new java.awt.Color(44, 62, 80));
        lblMembreCount3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMembreCount3.setText("Membres : ");

        btnClub3.setBackground(new java.awt.Color(52, 152, 219));
        btnClub3.setForeground(new java.awt.Color(44, 62, 80));
        btnClub3.setText("Detail");
        btnClub3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClub3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtGerant3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClubName3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblClubName7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblMembreCount3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnClub3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClubName3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClubName7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGerant3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMembreCount3)
                .addGap(18, 18, 18)
                .addComponent(btnClub3)
                .addGap(90, 90, 90))
        );

        jPanel6.setBackground(new java.awt.Color(236, 240, 241));
        jPanel6.setPreferredSize(new java.awt.Dimension(120, 120));

        lblClubName4.setBackground(new java.awt.Color(204, 0, 0));
        lblClubName4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblClubName4.setForeground(new java.awt.Color(44, 62, 80));
        lblClubName4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClubName4.setText("jLabel5");

        lblClubName8.setBackground(new java.awt.Color(52, 99, 196));
        lblClubName8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblClubName8.setForeground(new java.awt.Color(44, 62, 80));
        lblClubName8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClubName8.setText("Gerant:");

        txtGerant4.setEditable(false);
        txtGerant4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGerant4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtGerant4.setEnabled(false);

        lblMembreCount4.setBackground(new java.awt.Color(52, 152, 219));
        lblMembreCount4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMembreCount4.setForeground(new java.awt.Color(44, 62, 80));
        lblMembreCount4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMembreCount4.setText("Membres : ");

        btnClub4.setBackground(new java.awt.Color(52, 152, 219));
        btnClub4.setForeground(new java.awt.Color(44, 62, 80));
        btnClub4.setText("Detail");
        btnClub4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClub4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnClub4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClubName4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblClubName8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblMembreCount4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(txtGerant4)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClubName4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClubName8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGerant4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMembreCount4)
                .addGap(18, 18, 18)
                .addComponent(btnClub4)
                .addGap(12, 12, 12))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(44, 62, 80));
        jLabel6.setText("Clubs");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(44, 62, 80));
        jLabel7.setText("Evenements");

        jPanel8.setBackground(new java.awt.Color(236, 240, 241));
        jPanel8.setPreferredSize(new java.awt.Dimension(120, 120));

        lblEventTitle1.setBackground(new java.awt.Color(52, 152, 219));
        lblEventTitle1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEventTitle1.setForeground(new java.awt.Color(44, 62, 80));
        lblEventTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEventTitle1.setText("jLabel2");

        lblParticipants1.setBackground(new java.awt.Color(52, 152, 219));
        lblParticipants1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblParticipants1.setForeground(new java.awt.Color(44, 62, 80));
        lblParticipants1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblParticipants1.setText("jLabel2");

        btnEvent1.setBackground(new java.awt.Color(52, 152, 219));
        btnEvent1.setForeground(new java.awt.Color(44, 62, 80));
        btnEvent1.setText("Detail");
        btnEvent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvent1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEventTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(lblParticipants1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnEvent1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEventTitle1)
                .addGap(18, 18, 18)
                .addComponent(lblParticipants1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnEvent1)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(236, 240, 241));
        jPanel9.setPreferredSize(new java.awt.Dimension(120, 120));

        lblEventTitle2.setBackground(new java.awt.Color(52, 152, 219));
        lblEventTitle2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEventTitle2.setForeground(new java.awt.Color(44, 62, 80));
        lblEventTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEventTitle2.setText("jLabel2");

        lblParticipants2.setBackground(new java.awt.Color(52, 152, 219));
        lblParticipants2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblParticipants2.setForeground(new java.awt.Color(44, 62, 80));
        lblParticipants2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblParticipants2.setText("jLabel2");

        btnEvent2.setBackground(new java.awt.Color(52, 152, 219));
        btnEvent2.setForeground(new java.awt.Color(44, 62, 80));
        btnEvent2.setText("Detail");
        btnEvent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvent2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEventTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(lblParticipants2, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEvent2)
                .addGap(20, 20, 20))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEventTitle2)
                .addGap(18, 18, 18)
                .addComponent(lblParticipants2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnEvent2)
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(236, 240, 241));
        jPanel10.setPreferredSize(new java.awt.Dimension(120, 120));

        lblEventTitle3.setBackground(new java.awt.Color(52, 152, 219));
        lblEventTitle3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEventTitle3.setForeground(new java.awt.Color(44, 62, 80));
        lblEventTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEventTitle3.setText("jLabel2");

        lblParticipants3.setBackground(new java.awt.Color(52, 152, 219));
        lblParticipants3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblParticipants3.setForeground(new java.awt.Color(44, 62, 80));
        lblParticipants3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblParticipants3.setText("jLabel2");

        btnEvent3.setBackground(new java.awt.Color(52, 152, 219));
        btnEvent3.setForeground(new java.awt.Color(44, 62, 80));
        btnEvent3.setText("Detail");
        btnEvent3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvent3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEventTitle3, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(lblParticipants3, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEvent3)
                .addGap(21, 21, 21))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEventTitle3)
                .addGap(18, 18, 18)
                .addComponent(lblParticipants3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnEvent3)
                .addContainerGap())
        );

        jPanel11.setBackground(new java.awt.Color(236, 240, 241));
        jPanel11.setPreferredSize(new java.awt.Dimension(120, 120));

        lblEventTitle4.setBackground(new java.awt.Color(52, 152, 219));
        lblEventTitle4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEventTitle4.setForeground(new java.awt.Color(44, 62, 80));
        lblEventTitle4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEventTitle4.setText("jLabel2");

        lblParticipants4.setBackground(new java.awt.Color(52, 152, 219));
        lblParticipants4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblParticipants4.setForeground(new java.awt.Color(44, 62, 80));
        lblParticipants4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblParticipants4.setText("jLabel2");

        btnEvent4.setBackground(new java.awt.Color(52, 152, 219));
        btnEvent4.setForeground(new java.awt.Color(44, 62, 80));
        btnEvent4.setText("Detail");
        btnEvent4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvent4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEventTitle4, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(lblParticipants4, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEvent4)
                .addGap(19, 19, 19))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEventTitle4)
                .addGap(18, 18, 18)
                .addComponent(lblParticipants4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnEvent4)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel10, jPanel11, jPanel3, jPanel4, jPanel5, jPanel6, jPanel8, jPanel9});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel10, jPanel11, jPanel3, jPanel4, jPanel5, jPanel6, jPanel8, jPanel9});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        new GestionClubs().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    private void btnClubsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClubsActionPerformed
        this.setVisible(false);
        new GestionClubs().setVisible(true);
    }//GEN-LAST:event_btnClubsActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // TODO add your handling code here:
            System.out.println("the id : " + id);
            lblUserName.setText(name);
            btnMyClub.setVisible(false);

            con = AppConfig.connexion();
            pst = con.prepareStatement("""
                SELECT club.id, club.nom as club_name, membre.nom AS gerant_name, COUNT(club_membre.id_membre) 
                AS 'membre_count' FROM club
                LEFT JOIN club_membre ON club.id = club_membre.id_club
                LEFT JOIN membre ON club.id_gerant = membre.id
                WHERE club.date_creation BETWEEN ? AND ? GROUP BY club.id, membre.nom
                ORDER BY COUNT(club_membre.id_membre) DESC limit 4;
            """);

            //determine the school year to show only the clubs of this school year
            LocalDate currentDate = LocalDate.now();
            int currentYear = currentDate.getMonthValue() >= 9 ? currentDate.getYear() : currentDate.getYear() - 1;
            int startingMonth = 9; // September
            int endingMonth = 8; // August of the next calendar year
            pst.setDate(1, java.sql.Date.valueOf(currentYear + "-" + startingMonth + "-01")); // Start date
            pst.setDate(2, java.sql.Date.valueOf((currentYear + 1) + "-" + endingMonth + "-31")); // End date

            rs = pst.executeQuery();

            int clubCount = 0;
            ids = new ArrayList();
            while (rs.next()) {
                clubCount++;
                String clubName = rs.getString("club_name");
                String gerantName = rs.getString("gerant_name");
                int membreount = rs.getInt("membre_count");
                int id = rs.getInt("id");
                ids.add(id);
                switch (clubCount) {
                    case 1:
                        lblClubName1.setText(clubName);
                        txtGerant1.setText(gerantName);
                        lblMembreCount1.setText("Membres : " + membreount);
                        btnClub1.setVisible(true);
                        break;
                    case 2:
                        lblClubName2.setText(clubName);
                        txtGerant2.setText(gerantName);
                        lblMembreCount2.setText("Membres : " + membreount);
                        btnClub2.setVisible(true);
                        break;
                    case 3:
                        lblClubName3.setText(clubName);
                        txtGerant3.setText(gerantName);
                        lblMembreCount3.setText("Membres : " + membreount);
                        btnClub3.setVisible(true);
                        break;
                    case 4:
                        lblClubName4.setText(clubName);
                        txtGerant4.setText(gerantName);
                        lblMembreCount4.setText("Membres : " + membreount);
                        btnClub4.setVisible(true);
                        break;
                }
                System.out.println(clubCount);
            }
            pst = con.prepareStatement("""
                                       select evenement.id as event_id, evenement.titre as event_title,count(paiement.id_membre)
                                       as membre_count from evenement inner join paiement on evenement.id = paiement.id_evenement
                                       GROUP by evenement.titre order by count(paiement.id_membre) desc;
                                       """);
            rs = pst.executeQuery();

            int eventCount = 0;
            ids = new ArrayList();
            while (rs.next()) {
                System.out.println("has next");
                eventCount++;
                String eventTitle = rs.getString("event_title");
                int membreCount = rs.getInt("membre_count");
                int id = rs.getInt("event_id");
                ids.add(id);
                switch (eventCount) {
                    case 1:
                        lblEventTitle1.setText(eventTitle);
                        lblParticipants1.setText("Participants : " + membreCount);
                        btnEvent1.setVisible(true);
                        break;
                    case 2:
                        lblEventTitle2.setText(eventTitle);
                        lblParticipants2.setText("Participants : " + membreCount);
                        btnEvent2.setVisible(true);
                        break;
                    case 3:
                        lblEventTitle3.setText(eventTitle);
                        lblParticipants3.setText("Participants : " + membreCount);
                        btnEvent3.setVisible(true);
                        break;
                    case 4:
                        lblEventTitle4.setText(eventTitle);
                        lblParticipants4.setText("Participants : " + membreCount);
                        btnEvent4.setVisible(true);
                        break;
                }
            }
            if (!role.equals("admin")) {
                gerantClubId();
                btnClubs.setVisible(false);
                btnEvents.setVisible(true);
                btnClub1.setVisible(false);
                btnClub2.setVisible(false);
                btnClub3.setVisible(false);
                btnClub4.setVisible(false);
                btnEvent1.setVisible(false);
                btnEvent2.setVisible(false);
                btnEvent3.setVisible(false);
                btnEvent4.setVisible(false);
                btnMyClub.setVisible(true);
            }

        } catch (SQLException ex) {
            System.out.println("" + ex.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnClub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClub1ActionPerformed
        // TODO add your handling code here:
        System.out.println(ids.get(0));
        this.setVisible(false);
        new GestionMembres(ids.get(0)).setVisible(true);
    }//GEN-LAST:event_btnClub1ActionPerformed

    private void btnClub2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClub2ActionPerformed
        // TODO add your handling code here:
        System.out.println(ids.get(1));
        this.setVisible(false);
        new GestionMembres(ids.get(1)).setVisible(true);
    }//GEN-LAST:event_btnClub2ActionPerformed

    private void btnClub3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClub3ActionPerformed
        // TODO add your handling code here:
        System.out.println(ids.get(2));
        this.setVisible(false);
        new GestionMembres(ids.get(2)).setVisible(true);
    }//GEN-LAST:event_btnClub3ActionPerformed

    private void btnClub4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClub4ActionPerformed
        // TODO add your handling code here:
        System.out.println(ids.get(3));
        this.setVisible(false);
        new GestionMembres(ids.get(3)).setVisible(true);
    }//GEN-LAST:event_btnClub4ActionPerformed

    private void btnEvent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvent1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEvent1ActionPerformed

    private void btnEvent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvent2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEvent2ActionPerformed

    private void btnEvent3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvent3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEvent3ActionPerformed

    private void btnEvent4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvent4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEvent4ActionPerformed

    public void gerantClubId(){
        try {
            pst = con.prepareStatement("select id from club where id_gerant = ?");
            pst.setInt(1, id);
            rs = pst.executeQuery();
            rs.next();
            clubId = rs.getInt("id");
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void btnMyClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyClubActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new GestionMembres(clubId).setVisible(true);
    }//GEN-LAST:event_btnMyClubActionPerformed

    private void btnEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventsActionPerformed
        // TODO add your handling code here:
        new GestionEvents(clubId,role).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEventsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClub1;
    private javax.swing.JButton btnClub2;
    private javax.swing.JButton btnClub3;
    private javax.swing.JButton btnClub4;
    private javax.swing.JButton btnClubs;
    private javax.swing.JButton btnEvent1;
    private javax.swing.JButton btnEvent2;
    private javax.swing.JButton btnEvent3;
    private javax.swing.JButton btnEvent4;
    private javax.swing.JButton btnEvents;
    private javax.swing.JButton btnMyClub;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblClubName1;
    private javax.swing.JLabel lblClubName2;
    private javax.swing.JLabel lblClubName3;
    private javax.swing.JLabel lblClubName4;
    private javax.swing.JLabel lblClubName5;
    private javax.swing.JLabel lblClubName6;
    private javax.swing.JLabel lblClubName7;
    private javax.swing.JLabel lblClubName8;
    private javax.swing.JLabel lblEventTitle1;
    private javax.swing.JLabel lblEventTitle2;
    private javax.swing.JLabel lblEventTitle3;
    private javax.swing.JLabel lblEventTitle4;
    private javax.swing.JLabel lblMembreCount1;
    private javax.swing.JLabel lblMembreCount2;
    private javax.swing.JLabel lblMembreCount3;
    private javax.swing.JLabel lblMembreCount4;
    private javax.swing.JLabel lblParticipants1;
    private javax.swing.JLabel lblParticipants2;
    private javax.swing.JLabel lblParticipants3;
    private javax.swing.JLabel lblParticipants4;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtGerant1;
    private javax.swing.JTextField txtGerant2;
    private javax.swing.JTextField txtGerant3;
    private javax.swing.JTextField txtGerant4;
    // End of variables declaration//GEN-END:variables
}
